[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true }
macroquad = { workspace = true }
macroquad-tiled = { workspace = true }
macroquad-platformer = { workspace = true }
